spring.application.name=evaluation-service
spring.datasource.url=jdbc:postgresql://localhost:5432/evaluationdb
spring.datasource.username=postgres
spring.datasource.password=0000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8082